#!/bin/bash

SHELL_PATH=$(cd "$(dirname "$0")";pwd)

declare -A ALLOWED_HEADER_KEYS
declare -A ALLOWED_HEADER_VALUES

WAF_CONFIG_FILE="${SHELL_PATH}/waf-config.json"
WAF_RULE_TEMPLATE_FILE="${SHELL_PATH}/waf-rule.json.template"

WAF_CONFIG_FILE_CONTENT=$(cat "$WAF_CONFIG_FILE")
ALLOWED_HEADER_KEYS_STRING=$(jq -r '.AllowedHeaderValueMap | keys[]' <<< $WAF_CONFIG_FILE_CONTENT)
ALLOWED_HEADER_ARRAY_INDEX=0
while IFS= read -r key; do
    ALLOWED_HEADER_KEYS[$ALLOWED_HEADER_ARRAY_INDEX]=$key
    ALLOWED_HEADER_VALUES[$ALLOWED_HEADER_ARRAY_INDEX]=$(jq ".AllowedHeaderValueMap[\"$key\"]" $WAF_CONFIG_FILE)
    ALLOWED_HEADER_VALUES[$ALLOWED_HEADER_ARRAY_INDEX]=$(echo ${ALLOWED_HEADER_VALUES[$ALLOWED_HEADER_ARRAY_INDEX]} | tr -d '"')
    ALLOWED_HEADER_ARRAY_INDEX=$((ALLOWED_HEADER_ARRAY_INDEX+1))
done <<< "$ALLOWED_HEADER_KEYS_STRING"
ALLOWED_HEADER_ARRAY_SIZE="${#ALLOWED_HEADER_KEYS[@]}"

echo "ALLOWED_HEADER_KEYS: ${ALLOWED_HEADER_KEYS[@]}"
echo "ALLOWED_HEADER_VALUES: ${ALLOWED_HEADER_VALUES[@]}"
echo "ALLOWED_HEADER_ARRAY_SIZE: $ALLOWED_HEADER_ARRAY_SIZE"

ALLOWED_HEADER_NAME=$(jq '.AllowedHeaderName' $WAF_CONFIG_FILE | tr -d '"')
echo "ALLOWED_HEADER_NAME: $ALLOWED_HEADER_NAME"

ALLOWED_HEADER_ARRAY_LAST_INDEX=$(($ALLOWED_HEADER_ARRAY_SIZE-1))
ALLOWED_HEADER_ARRAY_INDEX=$(shuf -i 0-$ALLOWED_HEADER_ARRAY_LAST_INDEX -n 1)
PICKED_HEADER_KEY=${ALLOWED_HEADER_KEYS[$ALLOWED_HEADER_ARRAY_INDEX]}
PICKED_HEADER_VALUE=${ALLOWED_HEADER_VALUES[$ALLOWED_HEADER_ARRAY_INDEX]}
PICKED_HEADER_VALUE_B64=$(echo -n "$PICKED_HEADER_VALUE" | base64)

echo "PICKED_HEADER_KEY: $PICKED_HEADER_KEY"
echo "PICKED_HEADER_VALUE: $PICKED_HEADER_VALUE"
echo "PICKED_HEADER_VALUE_B64: $PICKED_HEADER_VALUE_B64"

WAF_RULE_STRING=$(jq -c . $WAF_RULE_TEMPLATE_FILE)
WAF_RULE_STRING=$(echo $WAF_RULE_STRING | sed "s/PA_ALLOWED_HEADER_NAME/$ALLOWED_HEADER_NAME/g;s/PA_ALLOWED_HEADER_VALUE/$PICKED_HEADER_VALUE_B64/g")
echo "WAF_RULE_STRING: $WAF_RULE_STRING"

WAF_WEB_ACL_NAME=$(jq '.WebACLName' $WAF_CONFIG_FILE | tr -d '"')
WAF_WEB_ACL_ID=$(jq '.WebACLId' $WAF_CONFIG_FILE | tr -d '"')
WAF_WEB_ACL_SCOPE=$(jq '.WebACLScope' $WAF_CONFIG_FILE | tr -d '"')
WAF_WEB_ACL_REGION=$(jq '.WebACLRegion' $WAF_CONFIG_FILE | tr -d '"')

echo "WAF_WEB_ACL_NAME: $WAF_WEB_ACL_NAME"
echo "WAF_WEB_ACL_ID: $WAF_WEB_ACL_ID"
echo "WAF_WEB_ACL_SCOPE: $WAF_WEB_ACL_SCOPE"
echo "WAF_WEB_ACL_REGION: $WAF_WEB_ACL_REGION"

WAF_WEB_ACL_LOCK_TOKEN=$(aws wafv2 get-web-acl \
                            --name $WAF_WEB_ACL_NAME \
                            --id $WAF_WEB_ACL_ID \
                            --scope $WAF_WEB_ACL_SCOPE \
                            --region $WAF_WEB_ACL_REGION \
                            --output text --query 'LockToken')

aws wafv2 update-web-acl \
    --name $WAF_WEB_ACL_NAME \
    --id $WAF_WEB_ACL_ID \
    --scope $WAF_WEB_ACL_SCOPE \
    --lock-token $WAF_WEB_ACL_LOCK_TOKEN \
    --region $WAF_WEB_ACL_REGION \
    --default-action Block={} \
    --visibility-config SampledRequestsEnabled=true,CloudWatchMetricsEnabled=true,MetricName=$WAF_WEB_ACL_NAME \
    --rules $WAF_RULE_STRING > /dev/null 2>&1


WAF_WEB_ACL_RULE_INDEX_BUCKET=$(jq '.WebACLRuleIndexBucket' $WAF_CONFIG_FILE | tr -d '"')
WAF_WEB_ACL_RULE_INDEX_OBJECT_KEY=$(jq '.WebACLRuleIndexObjectKey' $WAF_CONFIG_FILE | tr -d '"')
mkdir -p "$SHELL_PATH/output/"
WAF_WEB_ACL_RULE_INDEX_FILE="$SHELL_PATH/output/$WAF_WEB_ACL_RULE_INDEX_OBJECT_KEY"
echo $PICKED_HEADER_KEY | tee "$WAF_WEB_ACL_RULE_INDEX_FILE" > /dev/null 2>&1
aws s3api put-object \
    --bucket $WAF_WEB_ACL_RULE_INDEX_BUCKET \
    --key $WAF_WEB_ACL_RULE_INDEX_OBJECT_KEY \
    --body $WAF_WEB_ACL_RULE_INDEX_FILE > /dev/null 2>&1
WAF_WEB_ACL_RULE_INDEX_DISTRIBUTION_ID=$(jq '.WebACLRuleIndexDistributionId' $WAF_CONFIG_FILE | tr -d '"')
aws cloudfront create-invalidation \
    --distribution-id $WAF_WEB_ACL_RULE_INDEX_DISTRIBUTION_ID \
    --paths "/$WAF_WEB_ACL_RULE_INDEX_OBJECT_KEY" > /dev/null 2>&1

echo "WAF_WEB_ACL_RULE_INDEX_BUCKET: $WAF_WEB_ACL_RULE_INDEX_BUCKET"
echo "WAF_WEB_ACL_RULE_INDEX_OBJECT_KEY: $WAF_WEB_ACL_RULE_INDEX_OBJECT_KEY"
echo "WAF_WEB_ACL_RULE_INDEX_FILE: $WAF_WEB_ACL_RULE_INDEX_FILE"
echo "WAF_WEB_ACL_RULE_INDEX_DISTRIBUTION_ID: $WAF_WEB_ACL_RULE_INDEX_DISTRIBUTION_ID"
